### ISSUE TITLE
Can't roll back to specified block index: 278270 doesn't exist in database

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterblock#100]
Start bitcoin-testnet, and counterparty-testnet (Fed Node 1.1.0):
```
[INFO] Running v1.0.0 of counterparty-server.
[INFO] Running v9.49.4 of counterparty-lib.
[INFO] Acquiring lock.
[INFO] Connecting to database.
[INFO] Connecting to backend.
[INFO] Starting API Server.
[INFO] Resuming parsing.
```

Start counterblock-testnet, stop it, and start it again:

```
WARNING:startup: Support email setting not set: To enable, please specify an email for the 'support-email' setting in your counterblockd.conf
DEBUG:__init__: starting counterblock.lib.processor.startup.start_api
INFO:startup: Starting up RPC API handler...
DEBUG:blockfeed: Enabled Message Processor Functions [{'function': <function handle_exceptional at 0x7f882f2586e0>, 'priority': 65535, 'enabled': True, 'name': 'counterblock.lib.processor.messages.handle_exceptional'}, {'function': <function handle_invalid at 0x7f882f258758>, 'priority': 65534, 'enabled': True, 'name': 'counterblock.lib.processor.messages.handle_invalid'}, {'function': <function parse_insert at 0x7f882f2587d0>, 'priority': 65533, 'enabled': True, 'name': 'counterblock.lib.processor.messages.parse_insert'}, {'function': <function handle_reorg at 0x7f882f258848>, 'priority': 65532, 'enabled': True, 'name': 'counterblock.lib.processor.messages.handle_reorg'}, {'function': <function parse_issuance at 0x7f882f2588c0>, 'priority': 65531, 'enabled': True, 'name': 'counterblock.lib.processor.messages.parse_issuance'}, {'function': <function parse_balance_change at 0x7f882f258938>, 'priority': 65530, 'enabled': True, 'name': 'counterblock.lib.processor.messages.parse_balance_change'}, {'function': <function parse_trade_book at 0x7f882f2589b0>, 'priority': 65529, 'enabled': True, 'name': 'counterblock.lib.processor.messages.parse_trade_book'}, {'function': <function parse_broadcast at 0x7f882f258a28>, 'priority': 65528, 'enabled': True, 'name': 'counterblock.lib.processor.messages.parse_broadcast'}, {'function': <function parse_for_socketio at 0x7f882f258aa0>, 'priority': 65527, 'enabled': True, 'name': 'counterblock.lib.processor.messages.parse_for_socketio'}]
DEBUG:blockfeed: Enabled Block Processor Functions []
Traceback (most recent call last):
  File "/home/xcp/federatednode_build/env.counterblock/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/xcp/federatednode_build/env.counterblock/local/lib/python2.7/site-packages/counterblock/lib/blockfeed.py", line 163, in process_cp_blockfeed
    config.state['my_latest_block'] = database.rollback(my_latest_block['block_index'])
  File "/home/xcp/federatednode_build/env.counterblock/local/lib/python2.7/site-packages/counterblock/lib/database.py", line 202, in rollback
    raise Exception("Can't roll back to specified block index: %i doesn't exist in database" % max_block_index)
Exception: Can't roll back to specified block index: 278270 doesn't exist in database
<Greenlet at 0x7f882edf0a50: process_cp_blockfeed(<zmq.green.core._Socket object at 0x7f882edebef0>)> failed with Exception

```
Restart doesn't help, it causes the same error.

Is this a temporary error until bitcoin-testnet downloads that block?

**Comment by robby-dermody** [comment]
hmm, launching counterblock manually with the reparse option (`sudo su -s /bin/bash -c 'counterblock --reparse' xcpd`) should fix that, but I'm not sure ATM what's causing that...

**Comment by robby-dermody** [comment]
These issues should now be fixed in newest versions. Reopen if not
