### ISSUE TITLE
AttributeError: 'module' object has no attribute 'LOG'

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterblock#111]
This is the latest `counterblock` from yesterday, but last entries in its log are dated 02-14, so it probably didn't work since then. 
```
$ sudo su -s /bin/bash -c 'counterblock --config-file /home/xcp/.config/counterblock/server.testnet.conf server' xcpd
Traceback (most recent call last):
  File "/usr/local/bin/counterblock", line 9, in <module>
    load_entry_point('counterblock==1.1.0', 'console_scripts', 'counterblock')()
  File "/home/xcp/federatednode_build/env.counterblock/local/lib/python2.7/site-packages/counterblock/__init__.py", line 5, in server_main
    server.main()
  File "/home/xcp/federatednode_build/env.counterblock/local/lib/python2.7/site-packages/counterblock/counterblock/server.py", line 98, in main
    log.set_up(args.verbose)
  File "/home/xcp/federatednode_build/env.counterblock/local/lib/python2.7/site-packages/counterblock/counterblock/counterblock/lib/log.py", line 26, in set_up
    fileh = logging.handlers.RotatingFileHandler(config.LOG, maxBytes=MAX_LOG_SIZE, backupCount=MAX_LOG_COUNT)
AttributeError: 'module' object has no attribute 'LOG'
```
Edit: I knew I'd seen this before, but I couldn't find it... I before opened a similar bug here: https://github.com/CounterpartyXCP/federatednode_build/issues/204
But now that shouldn't matter any more since the code doesn't use numpy any more.

**Comment by robby-dermody** [comment]
should be fixed
