### ISSUE TITLE
 Failed to apply $inc operations to current value

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterblock#113]
INFO:messages: Procesed debit bal change from tx 218058 :: {'new_balance': 645000000, 'block_index': 319270, 'quantity_normalized': -0.5, 'block_time': datetime.datetime(2014, 9, 5, 22, 15, 6), 'asset': u'XCP', 'new_balance_normalized': 6.45, 'address': u'191p6NrS1PCXQ3nwvSbGjEm8sZGEt5uHy9', '_id': ObjectId('5503695b01f90b7e4f6326c7'), 'quantity': -50000000}
Traceback (most recent call last):
  File "/home/xcp/federatednode_build/env.counterblock/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/xcp/federatednode_build/env.counterblock/lib/python2.7/site-packages/counterblock/lib/blockfeed.py", line 253, in process_cp_blockfeed
    parse_block(block_data)
  File "/home/xcp/federatednode_build/env.counterblock/lib/python2.7/site-packages/counterblock/lib/blockfeed.py", line 117, in parse_block
    cmd = parse_message(msg)
  File "/home/xcp/federatednode_build/env.counterblock/lib/python2.7/site-packages/counterblock/lib/blockfeed.py", line 100, in parse_message
    cmd = function['function'](msg, msg_data) or None
  File "/home/xcp/federatednode_build/env.counterblock/lib/python2.7/site-packages/counterblock/lib/processor/messages.py", line 77, in parse_issuance
    assets.parse_issuance(config.mongo_db, msg_data, config.state['cur_block']['block_index'], config.state['cur_block'])
  File "/home/xcp/federatednode_build/env.counterblock/lib/python2.7/site-packages/counterblock/lib/components/assets.py", line 113, in parse_issuance
    "$push": {'_history': tracked_asset} }, upsert=False)
  File "/home/xcp/federatednode_build/env.counterblock/lib/python2.7/site-packages/pymongo/collection.py", line 552, in update
    _check_write_command_response(results)
  File "/home/xcp/federatednode_build/env.counterblock/lib/python2.7/site-packages/pymongo/helpers.py", line 209, in _check_write_command_response
    raise OperationFailure(error.get("errmsg"), error.get("code"), error)
OperationFailure: Failed to apply $inc operations to current value ((NumberLong)5200000000000000000) for document {_id: ObjectId('54dd6fcca12b2b7404015719')}
<Greenlet at 0x7f7598ab9410: process_cp_blockfeed(<zmq.green.core._Socket object at 0x7f759cdc0738>)> failed with OperationFailure

**Comment by robby-dermody** [comment]
So this is still an issue?

**Comment by ouziel-slama** [comment]
yep, an user reports the same error.

**Comment by robby-dermody** [comment]
They should try launching it from the console with --reparse... If that fixes it, we can increment db_version in config.py to force a counterblock reparse for everyone
