### ISSUE TITLE
pip install counterblock fails

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterblock#136]
I can't find or install counterblock in pip2 or pip3 repos.

```
user@server ~ $ sudo pip2 install counterblock
Downloading/unpacking counterblock
  Could not find any downloads that satisfy the requirement counterblock
Cleaning up...
No distributions at all found for counterblock
Storing debug log for failure in /root/.pip/pip.log
```

Log:

```
user@server ~ $ sudo cat /root/.pip/pip.log
[sudo] password for user:
------------------------------------------------------------
/usr/bin/pip2 run on Mon Nov 16 02:25:19 2015
Downloading/unpacking counterblock
  Getting page https://pypi.python.org/simple/counterblock/
  Could not fetch URL https://pypi.python.org/simple/counterblock/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/counterblock/ when looking for download links for counterblock
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for counterblock:
  * https://pypi.python.org/simple/counterblock/
  Getting page https://pypi.python.org/simple/counterblock/
  Could not fetch URL https://pypi.python.org/simple/counterblock/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/counterblock/ when looking for download links for counterblock
  Could not find any downloads that satisfy the requirement counterblock
Cleaning up...
No distributions at all found for counterblock
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for counterblock
```

https://pypi.python.org/pypi?%3Aaction=search&term=counterblock&submit=search shows no results.
##

**Comment by unsystemizer** [comment]
Closing this because it works and also it's Python3 now
