### ISSUE TITLE
GeoIP resource 404'd

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterblock#177]
This URL appears to be no longer available, but is hard coded:
https://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz

This URL is possibly the same resource at a new location, but I'm not sure:
https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz

Issue here: /counterblock/lib/modules/counterwallet.py
```
        if download:
            logger.info("Downloading GeoIP.dat")
            # TODO: replace with pythonic way to do this!
            cmd = "cd '{}'; wget -N -q http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz; gzip -dfq GeoIP.dat.gz".format(config.data_dir)
            util.subprocess_cmd(cmd)
        else:
            logger.info("GeoIP.dat database up to date. Not downloading.")
    download_geoip_data()
    module_config['GEOIP'] = pygeoip.GeoIP(geoip_data_path)
```

Here is the error I get while standing up a new fednode:
```
$ fednode tail counterblock
Attaching to federatednode_counterblock_1
ERROR:server: Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterblock", line 9, in <module>
    load_entry_point('counterblock', 'console_scripts', 'counterblock')()
  File "/counterblock/counterblock/__init__.py", line 7, in server_main
    server.main()
  File "/counterblock/counterblock/server.py", line 146, in main
    StartUpProcessor.run_active_functions()
  File "/counterblock/counterblock/lib/processor/__init__.py", line 171, in run_active_functions
    func['function'](*args, **kwargs)
  File "/counterblock/counterblock/lib/modules/counterwallet.py", line 613, in init
    module_config['GEOIP'] = pygeoip.GeoIP(geoip_data_path)
  File "/usr/local/lib/python3.5/dist-packages/pygeoip/__init__.py", line 118, in __init__
    self._fp = codecs.open(filename, 'rb', ENCODING)
  File "/usr/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/counterblock/GeoIP.dat'
INFO:log: Logging txes to '/root/.cache/counterblock/log/server.tx.log'
INFO:module: Loading Plugin Module lib/modules/assets
INFO:module: Loading Plugin Module lib/modules/counterwallet
INFO:module: Loading Plugin Module lib/modules/dex
INFO:module: Loading Plugin Module lib/modules/transaction_stats
INFO:module: Loading Plugin Module lib/modules/betting
INFO:server: counterblock command specified: server
INFO:server: counterblock Version 1.4.0 starting ...
INFO:database: Connecting to mongoDB backend ...
INFO:cache: Connecting to redis @ redis
INFO:counterwallet: Loading config at: /root/.config/counterblock/counterwallet.conf
INFO:counterwallet: Armory-utxsvr hostname: armory-utxsvr
INFO:counterwallet: Checking/updating GeoIP.dat ...
INFO:counterwallet: Downloading GeoIP.dat
gzip: GeoIP.dat.gz: No such file or directory
b''
ERROR:server: Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterblock", line 9, in <module>
    load_entry_point('counterblock', 'console_scripts', 'counterblock')()
  File "/counterblock/counterblock/__init__.py", line 7, in server_main
    server.main()
  File "/counterblock/counterblock/server.py", line 146, in main
    StartUpProcessor.run_active_functions()
  File "/counterblock/counterblock/lib/processor/__init__.py", line 171, in run_active_functions
    func['function'](*args, **kwargs)
  File "/counterblock/counterblock/lib/modules/counterwallet.py", line 613, in init
    module_config['GEOIP'] = pygeoip.GeoIP(geoip_data_path)
  File "/usr/local/lib/python3.5/dist-packages/pygeoip/__init__.py", line 118, in __init__
    self._fp = codecs.open(filename, 'rb', ENCODING)
  File "/usr/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/counterblock/GeoIP.dat'
federatednode_counterblock_1 exited with code 0
```

**Comment by droplister** [comment]
See Issue #172.
