### ISSUE TITLE
 Unhandled Exception

### ISSUE THREAD

**Issue by longhoangwkm** [CounterpartyXCP/counterblock#179]
```
INFO:log: Logging txes to '/root/.cache/counterblock/log/server.testnet.tx.log'
INFO:module: Loading Plugin Module lib/modules/assets
INFO:module: Loading Plugin Module lib/modules/counterwallet
INFO:module: Loading Plugin Module lib/modules/dex
INFO:module: Loading Plugin Module lib/modules/transaction_stats
INFO:module: Loading Plugin Module lib/modules/betting
INFO:server: counterblock command specified: server
INFO:server: counterblock Version 1.4.0 starting ...
INFO:database: Connecting to mongoDB backend ...
INFO:cache: Connecting to redis @ redis.development
INFO:counterwallet: Loading config at: /root/.config/counterblock/counterwallet.testnet.conf
INFO:counterwallet: Armory-utxsvr hostname: bitcoind.development
INFO:counterwallet: Checking/updating GeoLite2-City.mmdb ...
INFO:counterwallet: Downloading GeoLite2-City.mmdb
b''
ERROR:server: Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterblock", line 9, in <module>
    load_entry_point('counterblock', 'console_scripts', 'counterblock')()
  File "/counterblock/counterblock/__init__.py", line 7, in server_main
    server.main()
  File "/counterblock/counterblock/server.py", line 146, in main
    StartUpProcessor.run_active_functions()
  File "/counterblock/counterblock/lib/processor/__init__.py", line 171, in run_active_functions
    func['function'](*args, **kwargs)
  File "/counterblock/counterblock/lib/modules/counterwallet.py", line 621, in init
    module_config['GEOIP'] = geoip2.database.Reader(geoip_data_path)
  File "/usr/local/lib/python3.5/dist-packages/geoip2/database.py", line 86, in __init__
    self._db_reader = maxminddb.open_database(fileish, mode)
  File "/usr/local/lib/python3.5/dist-packages/maxminddb/__init__.py", line 41, in open_database
    return maxminddb.reader.Reader(database, mode)
  File "/usr/local/lib/python3.5/dist-packages/maxminddb/reader.py", line 51, in __init__
    with open(database, 'rb') as db_file:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/counterblock/GeoLite2-City.mmdb'
```

**Comment by longhoangwkm** [comment]
@chiguireitor GeoLite2-City now require signup to download

**Comment by longhoangwkm** [comment]
https://github.com/wakumo/counterblock/commit/a69b3490f8e6f8ae104c5b5c3dfa0391f3d9e313#diff-26ff4ad6aeb6b816f884a9ceeb75a9beR609 is wrong now

**Comment by longhoangwkm** [comment]
```
INFO:log: Logging txes to '/root/.cache/counterblock/log/server.testnet.tx.log'
INFO:module: Loading Plugin Module lib/modules/assets
INFO:module: Loading Plugin Module lib/modules/counterwallet
INFO:module: Loading Plugin Module lib/modules/dex
INFO:module: Loading Plugin Module lib/modules/transaction_stats
INFO:module: Loading Plugin Module lib/modules/betting
INFO:server: counterblock command specified: server
INFO:server: counterblock Version 1.4.0 starting ...
INFO:database: Connecting to mongoDB backend ...
INFO:cache: Connecting to redis @ redis.development
INFO:counterwallet: Loading config at: /root/.config/counterblock/counterwallet.testnet.conf
INFO:counterwallet: Armory-utxsvr hostname: bitcoind.development
INFO:counterwallet: Checking/updating GeoLite2-City.mmdb ...
INFO:counterwallet: GeoLite2-City.mmdb database up to date. Not downloading.
WARNING:counterwallet: Support email setting not set: To enable, please specify an email for the 'support-email' setting in your counterblockd.conf
INFO:startup: Starting up counterparty block feed poller...
INFO:startup: Starting up RPC API handler...
```
block feed poller not work also... i'm investigating :(

**Comment by chiguireitor** [comment]
How did you include the Geolite db? manual download and mounting via volume?

**Comment by chiguireitor** [comment]
Added a fix to the lack of GeoLite database download, please check it and lmk

**Comment by longhoangwkm** [comment]
i signed up and download manually

**Comment by chiguireitor** [comment]
But it didn't crash on startup, right?

**Comment by longhoangwkm** [comment]
@chiguireitor yes, it didn't crash on startup but block feeding didn't running. I wanna to enable log to debug but don't know how

**Comment by chiguireitor** [comment]
ok, are you running counterblock and counterparty in containers or directly?

**Comment by longhoangwkm** [comment]
we are running in containers k8s gcloud

**Comment by longhoangwkm** [comment]
Here are stuck log:

```
INFO:log: Logging txes to '/root/.cache/counterblock/log/server.testnet.tx.log'
INFO:module: Loading Plugin Module lib/modules/assets
INFO:module: Loading Plugin Module lib/modules/counterwallet
INFO:module: Loading Plugin Module lib/modules/dex
INFO:module: Loading Plugin Module lib/modules/transaction_stats
INFO:module: Loading Plugin Module lib/modules/betting
INFO:server: counterblock command specified: server
INFO:server: counterblock Version 1.4.0 starting ...
INFO:database: Connecting to mongoDB backend ...
INFO:cache: Connecting to redis @ redis.development
INFO:counterwallet: Loading config at: /root/.config/counterblock/counterwallet.testnet.conf
INFO:counterwallet: Armory-utxsvr hostname: bitcoind.development
INFO:counterwallet: Checking/updating GeoLite2-City.mmdb ...
INFO:counterwallet: GeoLite2-City.mmdb database up to date. Not downloading.
WARNING:counterwallet: Support email setting not set: To enable, please specify an email for the 'support-email' setting in your counterblockd.conf
INFO:startup: Starting up counterparty block feed poller...
INFO:startup: Starting up RPC API handler...
```

**Comment by longhoangwkm** [comment]
Bitcoind 0.18.1
Indexd and counterparty latest version

**Comment by chiguireitor** [comment]
is your counterparty backend synced? indexd synced?

**Comment by longhoangwkm** [comment]
Indexd:
```
Wed, 05 Feb 2020 05:04:35 GMT indexd resynchronizing
Wed, 05 Feb 2020 05:04:35 GMT indexd ... { indexd:
   { blockId: '00000000000000b82a9820f356ae2530ab24aed93bdcccb6a9b0ebbfb6ac8680',
     height: 1664983 },
  bitcoind:
   { blockId: '00000000000000b82a9820f356ae2530ab24aed93bdcccb6a9b0ebbfb6ac8680',
     height: 1664983 } }
Wed, 05 Feb 2020 05:05:35 GMT indexd resynchronizing
Wed, 05 Feb 2020 05:05:35 GMT indexd ... { indexd:
   { blockId: '00000000000000b82a9820f356ae2530ab24aed93bdcccb6a9b0ebbfb6ac8680',
     height: 1664983 },
  bitcoind:
   { blockId: '00000000000000b82a9820f356ae2530ab24aed93bdcccb6a9b0ebbfb6ac8680',
     height: 1664983 } }
```

counterparty:
```
[2020-02-05 03:15:20][INFO] Block: 1664974 (1.07s, hashes: L:b1a6e / TX:052f6 / M:fdbee)
[2020-02-05 03:34:21][INFO] Block: 1664975 (0.95s, hashes: L:5ca88 / TX:9ca87 / M:30458)
[2020-02-05 03:46:23][INFO] Block: 1664976 (0.52s, hashes: L:e8ae0 / TX:0a7aa / M:95395)
[2020-02-05 04:00:18][INFO] Block: 1664977 (0.81s, hashes: L:29653 / TX:6d30b / M:8b56b)
[2020-02-05 04:20:27][INFO] Block: 1664978 (0.75s, hashes: L:7b7fb / TX:06c95 / M:8214b)
[2020-02-05 04:40:50][INFO] Block: 1664979 (1.07s, hashes: L:3ab03 / TX:56019 / M:4e63e)
[2020-02-05 04:50:22][INFO] Block: 1664980 (0.76s, hashes: L:03998 / TX:b0f7d / M:7a3e9)
[2020-02-05 04:52:08][INFO] Block: 1664981 (1.03s, hashes: L:3577d / TX:3ba86 / M:5ed80)
[2020-02-05 04:57:40][INFO] Block: 1664982 (0.35s, hashes: L:ef191 / TX:9285a / M:ca191)
[2020-02-05 05:00:59][INFO] Block: 1664983 (0.60s, hashes: L:52d1b / TX:7437d / M:ff252)
```

**Comment by longhoangwkm** [comment]
all services synced completely
