### ISSUE TITLE
Unhandled Exception geoip2

### ISSUE THREAD

**Issue by longhoangwkm** [CounterpartyXCP/counterblock#182]
Where did you get geo2ip file @chiguireitor. I used my file bot got a syntax error https://github.com/wakumo/counterblock/tree/master/geolite2-city

```
INFO:module: Loading Plugin Module lib/modules/assets
INFO:module: Loading Plugin Module lib/modules/counterwallet
INFO:module: Loading Plugin Module lib/modules/dex
INFO:module: Loading Plugin Module lib/modules/transaction_stats
INFO:module: Loading Plugin Module lib/modules/betting
INFO:server: counterblock command specified: server
INFO:server: counterblock Version 1.4.0 starting ...
INFO:database: Connecting to mongoDB backend ...
INFO:cache: Connecting to redis @ 127.0.0.1
INFO:counterwallet: Loading config 
INFO:counterwallet: Armory-utxsvr hostname: bitcoind.development
ERROR:server: Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterblock", line 9, in <module>
    load_entry_point('counterblock', 'console_scripts', 'counterblock')()
  File "/counterblock/counterblock/__init__.py", line 7, in server_main
    server.main()
  File "/counterblock/counterblock/server.py", line 146, in main
    StartUpProcessor.run_active_functions()
  File "/counterblock/counterblock/lib/processor/__init__.py", line 171, in run_active_functions
    func['function'](*args, **kwargs)
  File "/counterblock/counterblock/lib/modules/counterwallet.py", line 596, in init
    import geoip2.database
  File "/usr/local/lib/python3.5/dist-packages/geoip2/database.py", line 9, in <module>
    import maxminddb
  File "/usr/local/lib/python3.5/dist-packages/maxminddb/__init__.py", line 51
    raise ValueError(f"Unsupported open mode: {mode}")
                                                    ^
SyntaxError: invalid syntax
```

**Comment by longhoangwkm** [comment]
https://github.com/wakumo/counterblock/pull/2
