### ISSUE TITLE
Operations with large numbers on 32 bit system

### ISSUE THREAD

**Issue by Ignat99** [CounterpartyXCP/counterblock#68]
When you run on a 32 bit system, issue an error. Perhaps this is due to operations with large numbers?

uname -a:
Linux zo1.novalocal 3.8.0-19-generic #29-Ubuntu SMP Wed Apr 17 18:16:28 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

sudo python2.7 ./counterblockd.py   --data-dir=/home/xcp/.config/counterblockd-testnet --testnet --config-file=/home/xcp/.config/counterblockd-testnet/counterblockd.conf -v

2014-10-19 19:46:12,234 :: INFO :: Received message 9534: {u'category': u'issuances', u'message_index': 9534, u'timestamp': 1413727102, u'block_index': 208896, u'command': u'insert', u'bindings': u'{"asset": "LTBCOISEATS", "block_index": 208896, "call_date": 0, "call_price": 0.0, "callable": false, "description": "Seats for LTBCOIN hangout", "divisible": true, "fee_paid": 50000000, "issuer": "n4dEtPecQPbXofvEHHEYaK5fo7dnptnJxA", "locked": false, "quantity": 5000000000000000000, "source": "n4dEtPecQPbXofvEHHEYaK5fo7dnptnJxA", "status": "valid", "transfer": false, "tx_hash": "0dc0f597a8286c64d428671f8bd20ab0a105af5e0f1170a103f0047491a18e77", "tx_index": 354118}'} ...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/home/xcp/counterpartyd_build/dist/counterblockd/lib/blockfeed.py", line 329, in process_cpd_blockfeed
    assets.parse_issuance(mongo_db, msg_data, cur_block_index, cur_block)
  File "/home/xcp/counterpartyd_build/dist/counterblockd/lib/components/assets.py", line 112, in parse_issuance
    "$push": {'_history': tracked_asset} }, upsert=False)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 552, in update
    _check_write_command_response(results)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 205, in _check_write_command_response
    raise OperationFailure(error.get("errmsg"), error.get("code"), error)
OperationFailure: Failed to apply $inc operations to current value ((NumberLong)5000000000000000000) for document {_id: ObjectId('544122abbdd7437ef4ece90c')}
<Greenlet at 0x3cc8af0: process_cpd_blockfeed(<zmq.green.core._Socket object at 0x3d90870>)> failed with OperationFailure
##

**Comment by cryptcoin-junkey** [comment]
Why is this issue still active? IMO, there is less value to support 32bit servers.

**Comment by unsystemizer** [comment]
I don't know if it's still an issue (maybe it's been fixed?).

Some Raspberry Pi's are 32 bit. There's never been a discussion whether 32 bit OS should be ignored, as far as I remember. Or whether they should be supported...
